project_id = "jkizhhyuhksmsdndzfra"

[api]
enabled = true
url = "https://jkizhhyuhksmsdndzfra.supabase.co"

[db]
enabled = false

[realtime]
enabled = false

[storage]
enabled = false

[edge_functions]
enabled = true
[edge_functions.create-checkout]
verify_jwt = true