// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkizhhyuhksmsdndzfra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpraXpoaHl1aGtzbXNkbmR6ZnJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwODI1MjksImV4cCI6MjA1MzY1ODUyOX0.5JIbN8qe8VUGqAUozfklAf-b8xcsIPVDjIazI-pidak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);