// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmusrzauukoumapufcyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptdXNyemF1dWtvdW1hcHVmY3loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxOTE4MTAsImV4cCI6MjA1Mzc2NzgxMH0.i-vzTsjSDuZgEs5kJTBvYxj8DoON0Y_PhZi7KuJoe-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);